backend:
  name: github
  repo: eightsbinary/decap #แก้เป็น repo คุณ
  branch: main
  local_backend: true

media_folder: 'public/uploads'
public_folder: '/uploads'

collections:
  - name: 'blog'
    label: 'Blog'
    folder: 'src/content/blog'
    create: true
    slug: '{{slug}}'
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
